### ISSUE TITLE
Randomness does not look very much like user behavior

### ISSUE THREAD

**Issue by icefoxen** [essandess/isp-data-pollution#1]
My web browsing history is not random, and certainly doesn't tend to start from xfinity.com.  So it should be pretty easy for a tracker to differentiate pollution from real signal.  Especially if they can just use this script to generate some known-polluted data; then everything that doesn't look like that is user content.  (Proof left as an exercise to the reader for the moment, but I DO want to try it out sometime in my Copious Free Time...  Will post the results here if I ever get around to it.  Capture browsing history, capture output from this script, label each as real vs. pollution, run a binary classification algorithm of some sort on it (random forest?  KNN?) and see how well it does.)

A better technique might be to learn a lot of user behaviour, then permute that in weird ways to create noise.  Even better if you can combine a particular person's behaviour with a lot of other peoples'; that would actually disrupt your signal with that of other people, thus making it ~~impossible~~ much more difficult to tell who is whom.

**Comment by essandess** [comment]
> My web browsing history is not random, and certainly doesn't tend to start from xfinity.com.

There are both random and non-random components. The line in the code you're referring to is non-random. To bias the traffic to look more like your non-random browsing, fork the code and edit this line.

Because an approach like this is susceptible to both statistical attack and traffic anomalies, I would be interested in any statistical or other tests that illustrate susceptibilities. For what it's worth, I've looked at the traffic generated by this script and would myself would have a hard time identifying whether a lot of it was generated by my own family or not.

Alternate approaches may be more effective, but without evidence for this, the design rules of KISS and acknowledging that the perfect is the enemy of the good apply.

**Comment by OmenWild** [comment]
Along these same lines, by actually honoring the robots.txt files, and not downloading images, or JavaScript, or .css files, you are not imitating real browsing. It would be fairly straight forward for ISPs to filter out requests ONLY have the base HTML and non of the rest of the files. The sheer amount of data may make that harder, but hey, that's what big data is for.

**Comment by essandess** [comment]
If you believe that ISP DPI extends down to analysis of image downloads and correlation with robots.txt GETs, and would like more realistic traffic, then fork the code and comment out the lines that turn off image downloads and honor robots.txt.

I do not believe that this is necessary, and that the risks associated with downloading images during a random traversal outweigh ISP data exploitation.

**Comment by essandess** [comment]
I'm going to close this issue because browsing habit models include both random and non-random aspects.

The script has several hooks to include non-random habits: bias toward specific seed sites, a current preferred domain with stochastic time constant defaulted to a few hours, diurnal characteristics, and so forth.

Model parameters are all chosen based on either published or reasonable order-of-magnitude estimates of aggregate behavior.

Specific suggestions on model improvements or parameter choices—along with cited reasons for the model—are welcomed as individual issues.
