### ISSUE TITLE
feature proposal : random likes

### ISSUE THREAD

**Issue by wrnice** [essandess/isp-data-pollution#18]
Hello !

I just found your nice project and loved the idea ! I just set it running at home .

I was thinking that it could be cool to dispatch a bit of noise and nonsense in the Like business, and to erode the benefits of the advertising giants shareholders :)
I would even create my first facebook account for this.
I suppose it would need adding a parser to detect facebook, youtube , and the others like buttons, and send appropriate requests.
I have no clue about python, though. So I'm dropping the idea here, if someone is willing to pick it :)

Cheers and thank you for this sweet script.

**Comment by essandess** [comment]
Unencrypted traffic to Facebook, YouTube, and many other popular websites is not visible to your ISP because HTTPS is used. Therefore, random likes would affect Facebook's data, not your ISPs. And unlike many ISPs, participation on Facebook is optional. Randomly hitting likes would require Facebook authentication, in addition to a likely violation of Facebook's TOS.

Features not related to protecting user privacy from ISP exploitation are out-of-scope.

Consistent with this, be sure to use the EFF's browser plugin HTTPS Everywhere to use end-to-end encryption wherever possible.

**Comment by wrnice** [comment]
Thank you for your answer, it makes perfect sense as your work is geared towards ISPs.

My idea was to purposedely degrade Facebook / Google / Youtube efficiency to harvest our data, by purposedely authenticating to their services, but serving them bad quality data.
This could be the scope of a different project, you are right ! I'll keep following your progesses and make us of your script anyways.

I didn't think it could be against their TOS, I'd be curious to search for it.
